### ISSUE TITLE
what is this call for?

### ISSUE THREAD

**Issue by chovy** [eracknaphobia/plugin.video.nhlgcl#3]
https://mf.svc.nhl.com/ws/media/mf/v2.3/key/silk/mediaid/40699103/kid/20106583

I see it returns binary data and I don't see what its being used for.

**Comment by eracknaphobia** [comment]
It's actually what the m3u8 playlist calls to decrypt the video stream. I added it when i was trying to figure out the too many login attempts, it should probably be removed now if it's still in the main.py.

**Comment by chovy** [comment]
I'm running into this problem: `Sign-on restriction: Too many usage attempts`

Any idea what the threshold is? I was logging in every 10 minutes and generating game streams. But now I'm unable to watch video.

**Comment by eracknaphobia** [comment]
No really sure, seems to be 5-10 trys within 30 minutes. I haven't really attempt to do this purposely. If you using my addon once you successfully start a full live or archived game your cookies should be good for at least 6 hours. You don't ever need to logout in my addon now. It will check the cookies, if there still valid you're good otherwise it will perform a login. So you shouldn't get a too many sign on error unless you are using your account else where simultaneously.

**Comment by chovy** [comment]
Yeah, i'm looking at your code and porting some of it to node. Just for some exercise. I was just curious what the threshold you experienced was. Your addon works fine for me in Kodi.
