### ISSUE TITLE
New NHL.tv backend

### ISSUE THREAD

**Issue by feerlessleadr** [eracknaphobia/plugin.video.nhlgcl#37]
Hi - it looks like NHL.tv has moved away from bamtech backend to a new provider, so this addon no longer works with valid credentials. 

Any chance that this can be updated to support the new backend?

**Comment by rseanhall** [comment]
@eracknaphobia FYI, they seem to be requiring the `gCaptchaResponse` field now so this no longer works: https://github.com/eracknaphobia/plugin.video.nhlgcl/blob/e128961883ab9db6a8d4e33469f551eeaf1bc989/resources/lib/nhl_tv.py#L119

The response is HTTP 422 with the data:

```
{
  message: 'The given data was invalid.',
  errors: { gCaptchaResponse: [ 'Are you a robot?' ] }
}
```

**Comment by madano69** [comment]
Hello,

they are using some js library for generating captcha. I know that because I tried to login using nhltv page and I can see it in development console of firefox browser. So you can somehow check  (reverse engineering :) ) the communication between firefox and backend api and try to generate captcha using the same approach . I don't know what is possible in python since I am programmer, but not in python, but as fas as I know there is possibility to call js functions in python. Maybe later I will try to make more investigation but now I don't have really much time to do it.

**Comment by feerlessleadr** [comment]
Here is a link to a diff file that fixes the login issue. This is not my patch, I am just reposting what the user @juggie posted on the [kodi forums](https://forum.kodi.tv/showthread.php?tid=243756&pid=3117635#pid3117635).

https://pastebin.com/raw/5bk2v3XK
