### ISSUE TITLE
Can't Stream the Main broadcast on andriod device.

### ISSUE THREAD

**Issue by Hollier** [eracknaphobia/plugin.video.nhlgcl#8]
Hi, I'm using the Kodi addon on both an Andriod TV box and PC Attacked is the Kodi.log
[kodi.log](https://github.com/eracknaphobia/plugin.video.nhlgcl/files/1358119/kodi.log)

I can log in fine, using my Gamecenter login (Rogers customer). 
When I try and stream the broadcast it tries to stream but it does not pick up the steam. 
When I go to an alt camera view it works fine it's the main broadcast feed that is not working.

**Comment by eracknaphobia** [comment]
Yeah, I noticed that too. I'll be releasing a fix later today that should take care of that.

**Comment by eracknaphobia** [comment]
Please update to version 2017.10.3 from my repo and see if that fixes the issue.

**Comment by Hollier** [comment]
Great thanks, I will check it when I get home.

**Comment by monomorph** [comment]
Same issue here. Kodi Forum down. Where to get the "my repo"-zip... It's been some time I've been doing this. Current version is from the official Kodi repo.

???

**Comment by Hollier** [comment]
Go Here https://github.com/eracknaphobia/plugin.video.nhlgcl Click on the clone download button. 
Get the Zip file. 
in Kodi can't remember the steps but you can install Via zip file. 
Install it that way.

**Comment by monomorph** [comment]
Hey Hollier, got it working again. In a similar like you suggested on my own. Used the repo-zip from here: https://github.com/eracknaphobia/repo.eracknaphobia/blob/master/addons/plugin.video.nhlgcl/plugin.video.nhlgcl-2017.10.3.zip

- Pushed the zip with adbFire to my Philps Android TV. Install repo from zip and since "auto update" was selected after a minute or so it was fine again.
- Still got to do the same on my Fire TV stick and Nexus 7 devices...
- Kodi Forum still down - coincidence? ;-)

Thanks to you and eracknaphobia!

Sorry for misusing the Github/Dev issue thread.

**Comment by Hollier** [comment]
That did it. 

I had to uninstall and re-install the app. After that it works great. 

Thank you for the quick turnaround.

**Comment by ikvirsingh** [comment]
It's not working for me on my Nvidia Shield Android TV box after updating. I cleared cache also. I've attached my debug log if it helps. Thanks.

[debug.log](https://github.com/eracknaphobia/plugin.video.nhlgcl/files/1361458/debug.log)

**Comment by Hollier** [comment]
I had to reset the settings. For it to work 

CND = no preference
Stream quality Hd

Then it worked.

**Comment by Hollier** [comment]
I had to reset the settings. For it to work 

CND = no preference
Stream quality Hd

Then it worked.

**Comment by ikvirsingh** [comment]
Thanks @Hollier. It works now

**Comment by monomorph** [comment]
It's working on my Nexus 7 device now as well. Here I had to reset stream quality as mentioned by Hollier.

**Comment by hystyk28** [comment]
Fire TV Kodo 17.3 have paid sub to nhl
I have tried uninstalling/reinstalling-worked for preseason not for the new season...did they change something at the NHL mothers hip to kill this app?

**Comment by Hollier** [comment]
Chech you Setting I had to manually change them

Stream = HD Quality

Then it worked.

**Comment by ikvirsingh** [comment]
@eracknaphobia  It appears to me that the bug is once you change the CDN setting to Akamai or Level 3, it breaks the streaming URL resulting in a 404 response. The same also applies with the quality setting. If it is set to Best Available, it works fine for live and archived games, but breaks for Recaps and Extended Highlights.

**Comment by thedvrguy** [comment]
After the update to Kodi 17.5, I am only able to stream archives. On live games, I'm back to only being able to stream multi-cam.  Version 2017.10.3 fixed this same issue previously. Is there a newer version? Thanks very much.
